config-version: 2

name: "jaffle_shop_mdpi"
version: "1.0.0"
require-dbt-version: ">=1.9.0"

profile: default

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

seeds:
  jaffle_shop_mdpi:
    +schema: raw
    +materialized: table

models:
  jaffle_shop_mdpi:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: mart
      +materialized: table
