version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: jaffle_shop_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jaffle_shop
    ports:
      - "5430:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-db-volume:
